Feature tweak the world
dandgerson/pure-js-role-play-game pull request #2
Opened 2021-07-07 21:38 UTC by dandgerson

1. add absolute imports
2. add redux and tweak redux flow
3. add `processControls` module
4. add assets & config
5. add `keyState` reducer

2021-07-08 07:53 UTC, komarov-sergey commented on src/store/index.js
> +import { createStore, combineReducers } from 'redux'
о дааа!

2021-07-08 20:56 UTC, dandgerson commented on src/store/index.js
> +import { createStore, combineReducers } from 'redux'
ахаха))))

2021-07-08 21:35 UTC, dandgerson commented on src/store/index.js
> +import { createStore, combineReducers } from 'redux'
> о дааа!

@komarov-sergey психанул))

2021-07-12 19:59 UTC, ZarMarathon requested changes

2021-07-12 19:59 UTC, ZarMarathon commented on src/client/ClientWorld.js
> +    this.engine.renderSpriteFrame({
redux это хорошо, конечно, но как насчет отрисовать карту?

2021-07-13 22:56 UTC, dandgerson commented on src/client/ClientWorld.js
> +    this.engine.renderSpriteFrame({
@ZarMarathon Докинул. Благодарю за внимательность и ревью =)

2021-07-13 23:29 UTC, dandgerson commented on src/client/ClientWorld.js
> +    this.engine.renderSpriteFrame({
@komarov-sergey @ZarMarathon  вот Дима говорит, мы юзаем тут ООП, от того что инкапсуляция, а где  тут инкапсуляция, если классы проникают друг в друга дёргают методы друг друга как свои и шарят данные между собой, при этом изменяя их как придётся и генеря свои -- тоже без системно.

на мой взгляд пока каша полная!!

мы даже наследование не юзаем и докидываем что-то в прототайп, что выглядит очень странно.

юзая редакс я выделил три инкапсулированных модуля, которые общаются между собой посредством стора и чётко определённых вызовов.

про инкапсуляцию,

1. почему Game имеет метод initEngine ?
вместо того, чтобы у Engine был свой метод init

2. почему Game создаёт world, когда это явно должен делать Engine при инициалазции
и создавать и инициализировать World 

3. почему Game стартует Engine (engine.start()), когда engine должен стартовать при инициализации
Game  должен лишь знать что у Engine есть init() и всё.


4. Зачем Game знать о спрайтах, если sprites.js размапливает только Engine

5. Почему когда мы создаём инстансы wolrd и engine -- World мы кормим конфиг,  а Engine - нет, хотя и тот и другой взаимодействуют с конфигами

2021-07-14 00:08 UTC, godlinpz commented on src/client/ClientWorld.js
> +    this.engine.renderSpriteFrame({
1. потому что эта функция по-разному реализована для клиента и сервера.

2. Нет, `Engine` отвечает только за низкоуровневые операции. Те, которые могут быть перенесены в другую игру с другой архитектурой. А `Game` - как раз отвечает за архитектуру конкретной игры. А `World` - это часть конкретной архитектуры в данном случае, поэтому `Engine` с ним напрямую не общается.

3. `Engine` - это низкоуровневая часть, которая сама по себе не знает, когда начинать, а когда заканчивать работу - об этом знает `Game`, который как раз отвечает за логику игры. Поэтому он и главный.

4. По той же логике: `Engine` не знает и не должен знать, какие спрайты нужны конкретной игре (представленной классом `Game`). Об этом должен заботиться `Game.` Если мы заменим `Game` на другой класс, предоставляющий аналогичную логику, но для другой игры, с другими спрайтами, то это не должно влечь изменения в `Engine`.

5. `World` - это реализация ячеистой архитектуры. Однако, если мы захотим сделать другую игру, но так же на ячейках, нам достаточно будет изменить `Game`, а `World` мы сможем оставить таким же, потому что он не содержит логики, специфической для этой конкретной игры.

В целом, если я где-то оставил жесткие связи между объектами (например, я полагаюсь на то, что у `World` есть поле game, а  у `GameObject` есть поле cell), это значит, что либо я хотел в этом конкретном месте упростить код, либо где-то поторопился и недосмотрел. 

Но в той части, которая у нас уже есть, мне кажется, архитектурных проблем нет.

2021-07-14 07:45 UTC, dandgerson commented on src/client/ClientWorld.js
> +    this.engine.renderSpriteFrame({
@godlinpz Благодарю тебя. Стало гораздо понятней!!

2021-07-15 18:29 UTC, merged